import type {ImageSourcePropType} from 'react-native';

export const CHAT_STAMP_URLS: {[key: number]: ImageSourcePropType} = {
  1: require('./chat-stamp1.png'),
  2: require('./chat-stamp2.png'),
  3: require('./chat-stamp3.png'),
  4: require('./chat-stamp4.png'),
  5: require('./chat-stamp5.png'),
  6: require('./chat-stamp6.png'),
  7: require('./chat-stamp7.png'),
  8: require('./chat-stamp8.png'),
  9: require('./chat-stamp9.png'),
  10: require('./chat-stamp10.png'),
  11: require('./chat-stamp11.png'),
  12: require('./chat-stamp12.png'),
  13: require('./chat-stamp13.png'),
  14: require('./chat-stamp14.png'),
  15: require('./chat-stamp15.png'),
  16: require('./chat-stamp16.png'),
  17: require('./chat-stamp17.png'),
  18: require('./chat-stamp18.png'),
  19: require('./chat-stamp19.png'),
  20: require('./chat-stamp20.png'),
  21: require('./chat-stamp21.png'),
  22: require('./chat-stamp22.png'),
  23: require('./chat-stamp23.png'),
  24: require('./chat-stamp24.png'),
  25: require('./chat-stamp25.png'),
  26: require('./chat-stamp26.png'),
  27: require('./chat-stamp27.png'),
  28: require('./chat-stamp28.png'),
} as const;

export const CHAT_STAMP_ICONS = [
  {id: 1, url: CHAT_STAMP_URLS[1]},
  {id: 2, url: CHAT_STAMP_URLS[2]},
  {id: 3, url: CHAT_STAMP_URLS[3]},
  {id: 4, url: CHAT_STAMP_URLS[4]},
  {id: 5, url: CHAT_STAMP_URLS[5]},
  {id: 6, url: CHAT_STAMP_URLS[6]},
  {id: 7, url: CHAT_STAMP_URLS[7]},
  {id: 8, url: CHAT_STAMP_URLS[8]},
  {id: 9, url: CHAT_STAMP_URLS[9]},
  {id: 10, url: CHAT_STAMP_URLS[10]},
  {id: 11, url: CHAT_STAMP_URLS[11]},
  {id: 12, url: CHAT_STAMP_URLS[12]},
  {id: 13, url: CHAT_STAMP_URLS[13]},
  {id: 14, url: CHAT_STAMP_URLS[14]},
  {id: 15, url: CHAT_STAMP_URLS[15]},
  {id: 16, url: CHAT_STAMP_URLS[16]},
  {id: 17, url: CHAT_STAMP_URLS[17]},
  {id: 18, url: CHAT_STAMP_URLS[18]},
  {id: 19, url: CHAT_STAMP_URLS[19]},
  {id: 20, url: CHAT_STAMP_URLS[20]},
  {id: 21, url: CHAT_STAMP_URLS[21]},
  {id: 22, url: CHAT_STAMP_URLS[22]},
  {id: 23, url: CHAT_STAMP_URLS[23]},
  {id: 24, url: CHAT_STAMP_URLS[24]},
  {id: 25, url: CHAT_STAMP_URLS[25]},
  {id: 26, url: CHAT_STAMP_URLS[26]},
  {id: 27, url: CHAT_STAMP_URLS[27]},
  {id: 28, url: CHAT_STAMP_URLS[28]},
] as const;
